### ISSUE TITLE
some small issues

### ISSUE THREAD

**Issue by Onur101010** [JW301/DingesWolf-Mathe1-Dorn-WS1516#10]
![20160127_115754](https://cloud.githubusercontent.com/assets/16744013/12611524/456b2270-c4ed-11e5-81c3-3f9488e4f6a4.jpg)

**Comment by jwtue** [comment]
6.23 Kein Mitschrieb zum Vergleich vorhanden, außerdem soll inhaltlich nichts gegenüber der Vorlesung geändert werden (siehe auch die Zeile darauf, dort wird explizit Bezug genommen auf die Reihenfolge der Parameter), bleibt also

alles andere wird gefixt

**Comment by Onur101010** [comment]
achso ok sry, ich dachte das sei wirklich vertauscht.
