### ISSUE TITLE
Errors in January 13 lecture 

### ISSUE THREAD

**Issue by jwtue** [JW301/DingesWolf-Mathe1-Dorn-WS1516#2]
Bei 6.15d) muss es heißen m|(a-b), m|(b-c) für die transivität.
Bei 6.18 müsste stehen b1=b2 (mod m), also runtergestellte zahlen und ein kongruenzrelationszeichen.

(Thanks to AW)

**Comment by DingTo** [comment]
6.18 sollte gefixt sein, kp wo / was genau bei 6.15 geändert werden muss.
